[workstations]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[workstations:vars]
target_user="b08x"
yadm_dotfiles_repo="git@github.com:b08x/dots.git"
enable_hybrid_graphics=true
enable_container_tools=true
enable_yadm_bootstrap=true
