---
- name: Restart dify
  listen: ai_dify restart
  ansible.builtin.systemd:
    name: "{{ item }}.service"
    state: restarted
    daemon_reload: true
  loop:
    - dify-sandbox
    - dify-api
    - dify-worker
    - dify-web
