---
- name: Deploy Langfuse Config (Vault)
  ansible.builtin.template:
    src: langfuse.env.j2
    dest: /opt/ai/config/langfuse.env
    owner: root
    group: ai-svc
    mode: "0640"
  notify: Restart langfuse

- name: Deploy Langfuse Quadlets
  ansible.builtin.template:
    src: langfuse-web.container.j2
    dest: /etc/containers/systemd/langfuse-web.container
    mode: "0644"
  notify: Restart langfuse

- name: Enable and start Langfuse
  ansible.builtin.systemd:
    name: langfuse-web.service
    state: started
    enabled: true
    daemon_reload: true

- name: Execute backup
  ansible.builtin.include_tasks: backup.yml
  tags: [never, backup]

- name: Execute restore
  ansible.builtin.include_tasks: restore.yml
  tags: [never, restore]
