# SPDX-License-Identifier: MIT-0
---
- name: Note that a reboot is required
  become: true
  ansible.builtin.file:
    path: /var/run/reboot-required
    state: touch
    owner: root
    group: root
    mode: "0644"
  listen: hardware reboot required
