---
- name: Restart databases
  listen: ai_databases restart
  ansible.builtin.systemd:
    name: "{{ item }}.service"
    state: restarted
    daemon_reload: true
  loop:
    - ai-postgres
    - ai-redis
    - ai-clickhouse
